[AuthService]
port = 1300
private_key_path = "/root/keys/private_key.pem"
public_key_path = "/root/keys/public_key.pem"
token_ttl = 60
refresh_token_ttl = 14
log_level = "debug"
redis_address = "auth_service_redis:6379"
redis_password = "QPTszALH527B6uGFnRewCk"